mgs: Prelive Profile
spring:
  cloud:
    discovery:
      enabled: true
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://123.49.44.41:5432/db_configuration_prod
    username: dev
    password: $dPp#P0stGr3@%
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

#Eureka
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 192.168.6.40
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.6.40:8761/eureka/

#Feign connection
feign:
  client:
    project-concept: http://123.49.44.40:8081/pps-pc/


